### ISSUE TITLE
Array.apply(null, new Array(paletteSize)).map(Boolean).map(function(a){ return { name: '0,0,0', count: 0 }; })

### ISSUE THREAD

**Issue by acelan86** [briangonzalez/rgbaster.js#21]
why  use `.map(Boolean)`? thank u

**Comment by AlfredJKwack** [comment]
Looks to me like it initializes the palette array with default data (ie blac color and 0 count).

```
var paletteSize = 10; 
var palette = Array.apply(null, new Array(paletteSize)).map(Boolean).map(function(a){ return { name: '0,0,0', count: 0 }; }); 
console.log(JSON.stringify(palette));
```

Returns: 

`[{"name":"0,0,0","count":0},{"name":"0,0,0","count":0},{"name":"0,0,0","count":0},{"name":"0,0,0","count":0},{"name":"0,0,0","count":0},{"name":"0,0,0","count":0},{"name":"0,0,0","count":0},{"name":"0,0,0","count":0},{"name":"0,0,0","count":0},{"name":"0,0,0","count":0}]`

**Comment by AlfredJKwack** [comment]
@briangonzalez I've checked on Chrome and there is no material difference when you remove the _.map(Boolean)_ from the line. Did you have something specific in mind when this was put in? Perhaps some legacy browser issue?

**Comment by AlfredJKwack** [comment]
Code was removed in PR #24
