### ISSUE TITLE
Png Image acquisition color has a problem.

### ISSUE THREAD

**Issue by Bad-Show** [briangonzalez/rgbaster.js#22]
I have a png image, and when I use the RGBaster to get the color of this picture, I get only black, whether it's dominant, secondary or palette. I do not know where the problem is. I put my png image into an attached file.
![noimg](https://cloud.githubusercontent.com/assets/13113226/21973822/3fadd002-dbfe-11e6-926f-704741389133.png)

**Comment by AlfredJKwack** [comment]
Hi,

Could you post a working example of the code with [codepen](https://codepen.io/) or [JsFiddle](https://jsfiddle.net/). That would help track down what is going on.

**Comment by AlfredJKwack** [comment]
A quick implementation on [codepen](https://codepen.io/anon/pen/egdXqE) of your image shows the results you describe.

The short answer is in issue #10 which concludes that rgba is not supported.

The longer answer is in the following issues already highlighted:
- #21 highlights that the palette is initialised with black. 
- #8 which highlights that transparent pixels are not skipped. I presume your PNG image has black pixels which are transparent to one degree or another.

As to why the _entire_ palette that is returned is black I would not hazard a guess at this moment, however it would be simpler to analyse if issue #12 were resolved with something like what @buffcode suggested.

**Comment by AlfredJKwack** [comment]
Further information,

From discussions [here](http://www.dreamincode.net/forums/topic/352957-canvas-how-to-prevent-zero-alpha-from-zeroing-rgb-channels/) and [here](https://stackoverflow.com/questions/11601302/html5-canvas-to-png-zeroes-all-channels-when-alpha-transparent) I understand the underlying browser API's Canvas.getContext and getImageData zero the RGB values when Alpha channel is zero (ie. transparent). Hence if there are a lot of transparent pixels, they will show up as black presumably.

**Comment by Bad-Show** [comment]
Thank you for your answer, which makes me understand what is going on, but how to solve this problem.

**Comment by AlfredJKwack** [comment]
There's something else going on here.

I've run a further test (see [this codepen](https://codepen.io/anon/pen/egdXqE)) which gets around issue #8 and #12 by pulling in an [updated version of the library](https://github.com/briangonzalez/rgbaster.js/compare/master...AlfredJKwack:master). Even though it ignores the transparent pixels RGBaster still shows the entire palette as black. Clearly it's not an issue with the underlying canvas and image data since [another test](https://codepen.io/anon/pen/ggmBYY) shows this works just fine browser-wise.

@briangonzalez @buffcode maybe you want to weigh in here as to what's actually going on with this image.

**Comment by AlfredJKwack** [comment]
I think I found the issue.

When RGBaster instantiates the canvas (on [line 7](https://github.com/briangonzalez/rgbaster.js/blob/master/rgbaster.js#L7)), no size is provided. As per the [W3C spec](https://www.w3.org/TR/2012/WD-html5-author-20120329/the-canvas-element.html#the-canvas-element) the browser will default the canvas to a width of 300, and a height of 150. 

```
var getContext = function(){
    return document.createElement("canvas").getContext('2d');
};
var ctx = getContext();
console.log(ctx.canvas.width); // 300
console.log(ctx.canvas.height); // 150
```

RGBaster draws the image onto the canvas so it can analyse it in later steps. When drawing the image onto the canvas (see [line 22](https://github.com/briangonzalez/rgbaster.js/blob/master/rgbaster.js#L22)) no size is given, neither in terms of source image nor destination canvas. 

```
      var context = getContext(imgObj.width, imgObj.height);
      context.drawImage(imgObj, 0, 0);
```

I believe this causes some issues as only a portion of the image is actually written to the canvas. When at a later step ([line 24](https://github.com/briangonzalez/rgbaster.js/blob/master/rgbaster.js#L24)) RGBaster reads the canvas it reads a rectangle the size of the original image, regardless of what the canvas size is.

I'm no expert on the canvas element and how its properties behave when writing and reading form areas outside the canvas. That being said, I did implement a change in the code which looks like it works. 

There are 2 changes. The first is with regards the getContext() function which accepts two variables and sets a width and height to the canvas

```
  var getContext = function(width, height){
    var canvas = document.createElement("canvas");
    canvas.setAttribute('width', width);
    canvas.setAttribute('height', height);  
    return canvas.getContext('2d');
  };
```
A quick test shows this sets the size as expected.
```
var ctx = getContext(800,500);
console.log(ctx.canvas.width);  //800
console.log(ctx.canvas.height); //500
```

The second change is when the above function is called. We just pass it the image's size.

`      var context = getContext(imgObj.width, imgObj.height);
`

Feel free to pull the updated file from my branch at [https://github.com/AlfredJKwack/rgbaster.js](https://github.com/AlfredJKwack/rgbaster.js) and let me know if it works for you.

**Comment by AlfredJKwack** [comment]
@Bad-Show Issue resolved in the above merged PR. 
Please update your copy of the repository and let us know if this works.

**Comment by Bad-Show** [comment]
Okay, you solved my problem, thanks again.
