### ISSUE TITLE
The same picture on ios and android Gets the RGB different

### ISSUE THREAD

**Issue by sivii** [briangonzalez/rgbaster.js#27]
Demo below:

```js
var bookImg = "http://cdn11.bookln.cn/10138_B657D15628884CAAE67BC1DB1A0699B8.jpg"
RGBaster.colors(bookImg, {
  paletteSize: 30,
  exclude: ['rgb(255,255,255)'],
  success: function (payload) {
    var rgb = payload.secondary
  }
});
```

**Comment by AlfredJKwack** [comment]
Hi @sivii thanks for bringing this to our attention.

Would you mind posting a screen grab of the results as provided by [this CodePen](https://codepen.io/anon/pen/wqyLJz)? I'm not sure there is much we can do about this but it's would be great to record instances for further analysis. Thanks

![grab](https://user-images.githubusercontent.com/557102/29487987-84b38edc-8502-11e7-965c-e152a6624aac.jpeg)
