### ISSUE TITLE
Posible to use without success: function()

### ISSUE THREAD

**Issue by BenjaminHoegh** [briangonzalez/rgbaster.js#28]
Posible to use without `success: function()` so it possible to make a `return`

**Comment by AlfredJKwack** [comment]
Hi @HawkonDK,

Do you have any suggestions on how to improve the implementation? What is the side effect you are looking to mitigate here?

Rgds,

**Comment by AlfredJKwack** [comment]
Hi @BenjaminHoegh (aka HawkonDK), 

It's been a year. How about we close this conversation?
