### ISSUE TITLE
dominated color is always black

### ISSUE THREAD

**Issue by BenjaminHoegh** [briangonzalez/rgbaster.js#29]
Error in the code make so the dominated color are black, and the secondary color are the dominated

**Comment by AlfredJKwack** [comment]
Hi,

Would you mind providing a demo and/or more information like source image, payload results etc.  A codePen or jsFiddle would be great or anything else hosted would do as well. 

Thanks.

**Comment by AlfredJKwack** [comment]
@hawkonDK

You appear to be interested in multiple libraries in parallel to solve some color functions. If that is the case you may want to check the below link:

https://github.com/briangonzalez/jquery.adaptive-backgrounds.js/issues/66#issuecomment-317081683

I hope its useful.

**Comment by AlfredJKwack** [comment]
Closing, no follow up. Demos work just fine.
