### ISSUE TITLE
Module support

### ISSUE THREAD

**Issue by SerdarSanri** [briangonzalez/rgbaster.js#32]
It would be nice if you add CommonJS and AMD support rather than implicitly adding window global namespace.

**Comment by AlfredJKwack** [comment]
PR's welcome,

I would think an implementation as seen on [UMD](https://github.com/umdjs/umd) would make sense. Perhaps [this one](https://github.com/umdjs/umd/blob/master/templates/commonjsStrictGlobal.js), considering the ask.

Thoughts?
