### ISSUE TITLE
import node module in js file

### ISSUE THREAD

**Issue by iam-robin** [briangonzalez/rgbaster.js#36]
Hi, thanks for your awesome module!

I've installed the node module with npm install rgbaster and now want to import the node module in one of my js files. But there is not just a single function I can reference.

Here is my Code:

```
import rgbaster from './rgbaster';

RGBaster.colors(img, {
  success: function(payload) {
    // You now have the payload.
    console.log(payload.dominant);
    console.log(payload.secondary);
    console.log(payload.palette);
  }
});
```

Thanks for the help!

**Comment by briangonzalez** [comment]
@iam-robin You're welcome. What is your question exactly so I can better assist?

**Comment by iam-robin** [comment]
I wanna use rgbaster in a chrome extension project. Therefore I wanna import rgbaster in one of my js files. I already installed the node module but don't know how to import it into my js file.

I've tried
`import rgbaster from './rgbaster';`
But it didn't work

**Comment by eltonmesquita** [comment]
Hello @iam-robin .
When working with a bundler like webpack, parcel or rollup, use `'rgbaster'` like this:
```js
    import rgbaster from 'rgbaster';
```
Period and slash `./` works for local modules.

**Comment by briangonzalez** [comment]
Oh, nice catch @eltonmesquita!
