### ISSUE TITLE
Transparency etc

### ISSUE THREAD

**Issue by liamcharmer** [briangonzalez/rgbaster.js#37]
Sorry viewing the transparency issues etc for PNG issues and couldnt quite figure out the answer from them. Is it possible or ?

**Comment by AlfredJKwack** [comment]
Yes, PNG can be processed, depends what you're looking for in terms of results The library provides results in [RGB](https://github.com/briangonzalez/rgbaster.js/blob/master/rgbaster.js#L94-L101), fully [transparent pixels](https://github.com/briangonzalez/rgbaster.js/blob/master/rgbaster.js#L88-L91) are completely ignored.

**Comment by liamcharmer** [comment]
Ah I see, only problem I have is that I intend to use primary colour as the background so it blends, so it'd it's a PNG and transparent then it ends up being black as the dominant colour ?

**Comment by liamcharmer** [comment]
Alrighty I think i'll have to use another library to be able to obtain the transparent pixels thank you ever so much though!!!

**Comment by AlfredJKwack** [comment]
Please do chime in when you find it. Good luck.
