### ISSUE TITLE
CORS test inverted in v2

### ISSUE THREAD

**Issue by AlfredJKwack** [briangonzalez/rgbaster.js#58]
Hi,

Functionally, what is the difference between the following two?

### TS code [from v2](https://github.com/briangonzalez/rgbaster.js/blob/8eca19975bc74b29e2d6f4755a3343c4f6ef87f3/src/helpers.ts#L15)
```
  if (src.startsWith('data')) img.crossOrigin = 'Anonymous'
```
and 

### JS code [from v1](https://github.com/briangonzalez/rgbaster.js/blob/426f853605c1fb0740fd06931950742db4318fb3/rgbaster.js#L20-L21)
```
    if ( imgSrc.substring(0,5) !== 'data:' )
      imgObj.crossOrigin = "Anonymous";
```

Unless I'm mistaken - which to be honest is quite possible after a long day's work - Version 2 of RGBaster has inverted the test for CORS handling of data url's.

**Comment by briangonzalez** [comment]
Oh snap, you're right!
