### ISSUE TITLE
Could you Elaborate in Readme?

### ISSUE THREAD

**Issue by AKluger** [briangonzalez/rgbaster.js#60]
I am attempting to use this based on your instructions and first have arrived at an error message regarding an improper header.  Perhaps I am missing something obvious so I just wanted to encourage anyone to elaborate in the readme i.e. mention any requirements and more of a step-by-step instruction if possible for someone newer to node in general and unfamiliar with typescript.

I have installed the package and am attempting to run function in a script within an html file.

**Comment by briangonzalez** [comment]
@AKluger 

Can you point us to what you have so far? Perhaps a git repo, code sandbox, jsfiddle, or something similar. 

We can help, and this process will shed light on what we need to add to the readme.

**Comment by AKluger** [comment]
I am simply using your example code as follows:

`import analyze from 'rgbaster';  
// in browser above line causes error "unexpected identifier"

function tester()   {
const result = await analyze('aja.jpg') // also supports base64 encoded image strings

console.log(`The dominant color is ${result[0].color} with ${result[0].count} occurrence(s)`)
// => The  dominant color is rgb(0,0,255) with 2 occurrence(s)
}

tester();`

The error occurs both when using a standalone js file and when putting the script directly into the html page.  When doing the latter, changing the script type to "module" from text/javascript changes the error message to "unexpected reserved word" on the line declaring the const result.

I have also tried installing typescript, changing the .js to a .ts file and labeling the function as async.  
I hope this provides some clarity to my predicament.  Thanks!

**Comment by GabeLemon** [comment]
Hey @AKluger, I too am getting the same issue. The issue is with the import from the module.

`/Users/a../Documents/nodeBS/index.js:1
(function (exports, require, module, __filename, __dirname) { import analyze from 'rgbaster'
                                                                                                                     ^^^^^^
SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
`

**Comment by briangonzalez** [comment]
The `import analyze from 'rgbaster'` line is only meant to be used inside a project with a `package.json` file where you've already run `npm install rgbaster`

After you `npm install` this repo into your own project, built UMD files will be downloaded and npm will know how to magically pull them in when you import the project.

If you want to paste the code directly into the browser, clone this repo, run `npm run build` and copy the contents of `rgbaster.umd.js`. UMD stands for _universal module definition_ and will work in the browser directly.

Or..you could grab the browser-ready file from unpkg: https://unpkg.com/rgbaster@2.1.1/dist/rgbaster.umd.js
