### ISSUE TITLE
Blocksize, length and transparent pixels

### ISSUE THREAD

**Issue by timse** [briangonzalez/rgbaster.js#8]
Not sure if I should open 3 issues or just aggregate them in one:
- why do you use the blocksize iteration? doesnt that mean you jump over 4/5 of all pixels?
- why do you use img.width \* img.height as the length? every pixels consists of 4 values (r,g,b,a) so data.length is ~4 times bigger - always. so you should always use it
- why not throw out transparent pixels? `if data[i+3] === 0`, they shouldnt account to anything, currently they make every image with transparency have `black` as the main color

**Comment by cmfcmf** [comment]
I totally agree with you @timse. It would be great if transparent pixels could be *sorted out* but still count for the main color (maybe add a parameter to allow "transparent" beeing the main color).

**Comment by AlfredJKwack** [comment]
@timse @buffcode @cmfcmf Closing the issue.
All 3 requested changes were merged along with 2 more items.
